# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       SaralHisab Blog
email:       'feedback@saralhisab.com'
description: 'Updates about saralhisab'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://story.saralhisab.com/' # The base hostname & protocol for your site
twitter:     'https://www.twitter.com/saralhisab'
github:      'https://github.com/ahesanali'
instagram:   'https://www.instagram.com/ahesanali_suthar/'
facebook:    'https://www.facebook.com/saralhisab'

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
#tipu search
tipue_search:
  include:
    pages: true
    collections: [apples, oranges]      
